version: '2'
services:
  jhapp-app:
    image: jhapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhapp-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=JhApp
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8081:8081
  jhapp-mongodb:
    extends:
      file: mongodb.yml
      service: jhapp-mongodb
